.PHONY: all
all:
	(cd d01 && nim compile --out=d01.bin --run input.txt)
	(cd d02 && nim compile --out=d02.bin --run input.txt)
	(cd d03 && nim compile --out=d03.bin --run input.txt)
	(cd d04 && nim compile --out=d04.bin --run input.txt)
