[package]
name = "d6"
version = "0.1.0"
authors = ["Will Fleming <will@flemi.ng>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
trees = "^0.2.1"
