.PHONY: all
all:
	(cd d01 && cargo run input.txt)
	(cd d02 && cargo run input.txt)
	(cd d03 && cargo run input.txt)
	(cd d04 && cargo run input.txt)
	(cd d05 && cargo run input.txt)
	(cd d06 && cargo run input.txt)
