[package]
name = "d19"
version = "0.1.0"
authors = ["Will Fleming <will@flemi.ng>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
intcode = { path = "../intcode" }
